MtOps2/urls.py
#-*- coding:utf8 -*-
"""MtOps2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from djauth_ext.forms import UserPwdUpdateForm


urlpatterns = [
    url( # grappelli URLS，在 url(r'^admin/', include(admin.site.urls)) 之前引用
        r'^grappelli/', include('grappelli.urls')
       ),
    url( # admin URL
        r'^admin/', include(admin.site.urls)
       ),
    url( # 包含 asset URL
        r'^asset/', include('asset.urls')
       ),
    url( # 包含 code_update URL
        r'^code-update/', include('code_update.urls')
       ),
    url(
        r'^dbop/', include('dbop.urls')
       ),
]

urlpatterns += [ # 使用 Django auth 提供的登录、注销视图
    url( # 平台登录
        r'^auth/user/login/$', auth_views.login, {'template_name': 'login_page.html'}, name='user-login'
       ),
    url( # 用户注销
        r'^auth/user/logout/$', auth_views.logout_then_login, name='user-logout'
       ),
    url( # 用户密码修改
        r'^auth/user/pwd-change/$', auth_views.password_change, {'template_name': 'djauth_ext/pwd_update_page.html', 'password_change_form': UserPwdUpdateForm,
        'post_change_redirect': auth_views.logout_then_login},
        name='djauth_ext-userpwd-change'
       ),
    url( # 包含 djauth_ext URL
        r'auth/', include('djauth_ext.urls')
       ),
]

asset/urls.py
# -*- coding:utf8 -*-
from django.conf.urls import url

from views import (ProjectCreateView, ProjectUpdateView, ProjectDeleteView, ProjectListView,
                   IdcCreateView, IdcUpdateView, IdcDeleteView, IdcListView, CabinetCreateView,
                   CabinetUpdateView, CabinetDeleteView, CabinetListView, HardwareCreateView,
                   HardwareUpdateView, HardwareDeleteView, HardwareListView, HostCreateView,
                   HostUpdateView, HostDeleteView, HostDetailView, HostListView,
                   )

urlpatterns = [
    url( # 创建软件项目
        r'project/create/$', ProjectCreateView.as_view(),
        name='asset-project-create',
       ),
    url( # 更新软件项目
        r'project/(?P<project_id>\d+)/update/$', ProjectUpdateView.as_view(),
        name='asset-project-update',
       ),
    url( # 删除软件项目
        r'project/(?P<project_id>\d+)/delete/$', ProjectDeleteView.as_view(),
        name='asset-project-delete',
       ),
#    url( # 项目详情
#        r'project/(?P<project_id>\d+)/detail/', ProjectDetailView.as_view(),
#        name='asset-project-detail',
#       ),
    url( # 软件项目列表
        r'project/list/$', ProjectListView.as_view(),
        name='asset-project-list',
       ),
    url( # 创建机房信息
        r'idc/create/$', IdcCreateView.as_view(),
        name='asset-idc-create',
       ),
    url( # 更新机房信息
        r'idc/(?P<idc_id>\d+)/update/$', IdcUpdateView.as_view(),
        name='asset-idc-update',
       ),
    url( # 删除机房
        r'idc/(?P<idc_id>\d+)/delete/$', IdcDeleteView.as_view(),
        name='asset-idc-delete',
       ),
    url( # 机房信息列表列表
        r'idc/list/$', IdcListView.as_view(),
        name='asset-idc-list',
       ),
    url( # 创建机柜信息
        r'cabinet/create/$', CabinetCreateView.as_view(),
        name='asset-cabinet-create',
       ),
    url( # 更新机柜信息
        r'cabinet/(?P<cabinet_id>\d+)/update/$', CabinetUpdateView.as_view(),
        name='asset-cabinet-update',
       ),
    url( # 删除机柜
        r'cabinet/(?P<cabinet_id>\d+)/delete/$', CabinetDeleteView.as_view(),
        name='asset-cabinet-delete',
       ),
    url( # 机柜信息列表
        r'cabinet/list/$', CabinetListView.as_view(),
        name='asset-cabinet-list',
       ),
    url( # 创建硬件信息
        r'hardware/create/$', HardwareCreateView.as_view(),
        name='asset-hardware-create',
       ),
    url( # 更新硬件信息
        r'hardware/(?P<hardware_id>\d+)/update/$', HardwareUpdateView.as_view(),
        name='asset-hardware-update',
       ),
    url( # 删除硬件信息
        r'hardware/(?P<hardware_id>\d+)/delete/$', HardwareDeleteView.as_view(),
        name='asset-hardware-delete',
       ),
    url( # 硬件信息列表
        r'hardware/list/$', HardwareListView.as_view(),
        name='asset-hardware-list',
       ),
    url( # 创建主机信息
        r'host/create/$', HostCreateView.as_view(),
        name='asset-host-create',
       ),
    url( # 更新主机信息
        r'host/(?P<host_id>\d+)/update/$', HostUpdateView.as_view(),
        name='asset-host-update',
       ),
    url( # 删除主机信息
        r'host/(?P<host_id>\d+)/delete/$', HostDeleteView.as_view(),
        name='asset-host-delete',
       ),
    url( # 主机详细信息
        r'host/(?P<host_id>\d+)/detail/$', HostDetailView.as_view(),
        name='asset-host-detail',
       ),
    url( # 主机信息列表
        r'host/list/$', HostListView.as_view(),
        name='asset-host-list',
       ),
]

dbop/urls.py
# -*-coding:utf8 -*-
from django.conf.urls import url
from views import (CTTaskCreateView, CTTaskUpdateView, CTTaskDeleteView,
                   CTTaskListView, ct_sub_task_create, )#ajax_cors_agent)

urlpatterns = [
    url( # 普通建表任务创建
        r'ct-task/create/$', CTTaskCreateView.as_view(),
        name='dbop-ct_task-create',
       ),
    url( # 更新普通建表任务
        r'ct-task/(?P<ct_task_id>\d+)/update/$', CTTaskUpdateView.as_view(),
        name='dbop-ct_task-update',
       ),
    url(
        r'ct-task/(?P<ct_task_id>\d+)/add-sql/$', ct_sub_task_create,
        name="dbop-ct_task-addsql",
       ),
    url( # 删除任务
        r'ct-task/(?P<ct_task_id>\d+)/delete/$', CTTaskDeleteView.as_view(),
        name='dbop-ct_task-delete',
       ),
    url( # 普通建表任务列表
        r'ct-task/list/$', CTTaskListView.as_view(),
        name='dbop-ct_task-list',
       ),
#    url(
#        r'cttask/(?P<ctmaintask_id>\d+)/detail/', 
#       ),
#    url( # ajax 代理视图
#        r'cttask/sql-textarex/ajaxpost-dbapi-check/$', ajax_cors_agent,
#        name='dbop-ajaxcors-agent',
#       ),
]

asset/models.py
# -*- coding:utf8 -*-
from django.db import models

from django.dispatch import receiver
from django.db.models.signals import post_save


class ProjectModel(models.Model):
    """
    软件项目模型
    """
    project_name = models.CharField(verbose_name=u'项目名称', db_column='project_name', max_length=50)
    project_alias = models.CharField(verbose_name=u'项目别名', db_column='project_alias', max_length=50,
                                     default='alias'
                                    )
    remark = models.TextField(verbose_name=u"备注", db_column='remark', help_text=u'项目描述')
    put_date = models.DateTimeField(verbose_name=u"记录添加时间", db_column='put_date', auto_now_add=True)

    def __unicode__(self):
        return self.project_name

    class Meta:
        db_table = 'asset_project'
        verbose_name = u'软件项目'
        verbose_name_plural = u'软件项目'


class IdcModel(models.Model):
    """
    机房模型
    """
    _LINK_TYPE = (
        ('0', u'联通'),
        ('1', u'电信'),
        ('2', u'教育网'),
        ('3', u'小运营商'),
        ('4', u'BGP'),
    )

    _POWER_TYPE = (
        ('0', u'交流电'),
        ('1', u'直流电'),
    )

    _IDC_STATUS = (
        ('0', u'在线'),
        ('1', u'下线'),
        ('2', u'测试'),
    )

    name = models.CharField(verbose_name=u'机房名称', db_column='name', max_length=50)
    address = models.CharField(verbose_name=u"机房地址" , db_column='address', max_length=128)
    contacts = models.CharField(verbose_name=u'机房联系人', db_column='contacts', max_length=50)
    phone = models.CharField(verbose_name=u'联系人电话', db_column='phone', max_length=50)
    link_type = models.CharField(verbose_name=u'链路类型', db_column='link_type', max_length=1, choices=_LINK_TYPE, default=0)
    bandwidth = models.FloatField(verbose_name=u'带宽／Gbps', db_column='bandwidth')
    cabinet_total = models.IntegerField(verbose_name=u'机柜数量', db_column='cabinet_tota')
    power_type = models.CharField(verbose_name=u'电源类型', db_column='power_type', max_length=1, choices=_POWER_TYPE)
    idc_status = models.CharField(verbose_name=u'机房状态', db_column='idc_status', max_length=1, choices=_IDC_STATUS)
    put_date = models.DateTimeField(verbose_name=u"记录添加时间", db_column='put_date', auto_now_add=True)
    remark = models.TextField(verbose_name=u'备注', db_column='remark')

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'asset_idc'
        verbose_name = u'机房'
        verbose_name_plural = u'机房'


class CabinetModel(models.Model):
    """
    机柜模型
    """
    _STANDBY_POWER = (
        ('0', u'支持'),
        ('1', u'不支持'),
    )
    name = models.CharField(verbose_name=u'机柜名称', db_column='name', max_length=50)
    idc = models.ForeignKey(IdcModel, verbose_name=u"所属机房", db_column='idc')
    standby_power = models.CharField(verbose_name=u'是否双路电', db_column='standby_power', max_length=1, choices=_STANDBY_POWER)
    u = models.IntegerField(verbose_name=u'机柜u 数', db_column='u', default=42)
    voltage = models.IntegerField(verbose_name=u'供电电压／V', db_column='voltage')
    put_date = models.DateTimeField(verbose_name=u"记录添加时间", db_column='put_date', auto_now_add=True)
    remark = models.TextField(verbose_name=u'备注', db_column='remark')

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'asset_cabinet'
        verbose_name = u'机柜'
        verbose_name_plural = u'机柜'


class HardwareModel(models.Model):
    """
    主机硬件配置
    """
    _NETWORK_CARD_RATE = (
        ('0', u'百兆'),
        ('1', u'千兆'),
        ('2', u'万兆'),
    )
    _DRAC = (
        ('0', u'支持'),
        ('1', u'不支持'),
    )
    _STANDBY_POWER = (
        ('0', u'支持'),
        ('1', u'不支持'),
    )

    model = models.CharField(verbose_name=u'型号', db_column='model', max_length=50)
    cpu = models.CharField(verbose_name=u'cpu 型号', db_column='cpu', max_length=50)
    cpu_total = models.IntegerField(verbose_name=u'cpu 个数', db_column='cpu_total')
    memory = models.FloatField(verbose_name=u'内存／G', db_column='memory')
    disk_type = models.CharField(verbose_name=u'硬盘类型', db_column='disk_type', max_length=50)
    disk_total = models.IntegerField(verbose_name=u'硬盘个数', db_column='disk_total')
    storage = models.IntegerField(verbose_name=u'存储容量／G', db_column='storage')
    network_card_total = models.IntegerField(verbose_name=u'网卡个数', db_column='network_card_total', default=1)
    network_card_rate = models.CharField(verbose_name=u'网卡速率', db_column='network_card_rate', max_length=1, choices=_NETWORK_CARD_RATE, default=0)
    drac = models.CharField(verbose_name=u'远程管理支持', db_column='drac', max_length=1, choices=_DRAC)
    standby_power = models.CharField(verbose_name=u'双电支持', db_column='standby_power', max_length=1, choices=_STANDBY_POWER, default=0)
    put_date = models.DateTimeField(verbose_name=u"记录添加时间", db_column='put_date', auto_now_add=True)
    remark = models.TextField(verbose_name=u'备注', db_column='remark', blank=True)

    def __unicode__(self):
        return self.model

    class Meta:
        db_table = 'asset_hardware'
        verbose_name = u'主机配置'
        verbose_name_plural = u'主机配置'


class HostModel(models.Model):
    """
    主机模型
    """
    _STATUS = (
        ('0', u'在线'),
        ('1', u'空闲'),
        ('2', u'报废'),
    )

    host_name = models.CharField(verbose_name=u'主机名', db_column='name', max_length=50, blank=True)
    sn = models.CharField(verbose_name=u'sn 服务码', db_column='sn', max_length=50)
    hardware = models.ForeignKey(HardwareModel, related_name='hardware_host',verbose_name=u"硬件配置", db_column='hardware')
    cabinet = models.ForeignKey(CabinetModel, related_name='cabinet_host', verbose_name=u"所属机柜", db_column='cabinet')
    os = models.CharField(verbose_name=u'操作系统', db_column='os', max_length=50)
    ip1 = models.GenericIPAddressField(verbose_name=u'网卡 1 ip 地址', db_column='ip1', blank=True, null=True)
    ip2 = models.GenericIPAddressField(verbose_name=u'网卡 2 ip 地址', db_column='ip2', blank=True, null=True)
    ip3 = models.GenericIPAddressField(verbose_name=u'网卡 3 ip 地址', db_column='ip3', blank=True, null=True)
    ip4 = models.GenericIPAddressField(verbose_name=u'网卡 4 ip 地址', db_column='ip4', blank=True, null=True)
    mac1 = models.CharField(verbose_name=u'网卡 1 mac 地址', db_column='mac1', max_length=50, blank=True)
    mac2 = models.CharField(verbose_name=u'网卡 2 mac 地址', db_column='mac2', max_length=50, blank=True)
    mac3 = models.CharField(verbose_name=u'网卡 3 mac 地址', db_column='mac3', max_length=50, blank=True)
    mac4 = models.CharField(verbose_name=u'网卡 4 mac 地址', db_column='mac4', max_length=50, blank=True)
    status = models.CharField(verbose_name=u'主机状态', db_column='status', max_length=1, choices=_STATUS)
    put_date = models.DateTimeField(verbose_name=u"记录添加时间", db_column='put_date', auto_now_add=True)
    remark = models.TextField(verbose_name=u'备注', db_column='remark', blank=True)

    def __unicode__(self):
        return self.host_name

    class Meta:
        db_table = 'asset_host'
        verbose_name = u'主机'
        verbose_name_plural = u'主机'


class HostHistoryModel(models.Model):
    """
    主机历史记录
    """
    host = models.ForeignKey(HostModel, verbose_name=u"主机", db_column='host')
    history = models.CharField(verbose_name=u'历史记录', db_column='history', max_length=100)
    put_date = models.DateTimeField(verbose_name=u"记录添加时间", db_column='put_date', auto_now_add=True)

    def __unicode__(self):
        return self.host.host_name

    class Meta:
        db_table = 'asset_host_history'
        verbose_name = u'主机历史记录'
        verbose_name_plural = u'主机历史记录'


@receiver(post_save, sender=HostModel)
def host_history(sender, instance, created, **kwargs):
    if created:
        history = u'%s %s 被创建' %(instance.host_name, instance.put_date.strftime('%Y-%m-%d %H:%M:%S'))
        history = HostHistoryModel(host=instance, history=history)
        history.save()

templates/asset/cabinet_create_page.html
{% extends "base_form_page.html" %}

{% block title %}MtOps2 | 创建机柜{% endblock %}

{% block page-header %}创建机柜{% endblock %}

templates/asset/cabinet_list_page.html
{% extends "base_table_page.html" %}

{% block title %}MtOps2 | 机柜列表{% endblock %}

{% block page-header %}机柜列表{% endblock %}

{% block panel-heading %}
    <a href="{% url 'asset-cabinet-create' %}" class="btn btn-success btn-sm {% if not perms.asset.add_cabinetmodel %}disabled{% endif %}" role="button">
        <i class="fa fa-plus-circle fa-fw"></i>创建机柜
    </a>
{% endblock %}

{% block thead-tr-th %}
    <th>ID</th>
    <th>机柜编号</th>
    <th>所属IDC</th>
    <th>支持双路电</th>
    <th>U数</th>
    <th>供电电压</th>
    <th>提交日期</th>
    <th>操作</th>
{% endblock %}

{% block tbody-tr-td %}
    <td>{{ object.id }}</td>
    <td>{{ object.name }}</td>
    <td>{{ object.idc }}</td>
    <td>{{ object.get_standby_power_display }}</td>
    <td>{{ object.u }}</td>
    <td>{{ object.voltage }}</td>
    <td>{{ object.put_date }}</td>
    <td>
        <a title="编辑" id="edit_{{ object.id }}" class="btn btn-success btn-xs {% if not perms.asset.change_cabinetmodel %}disabled{% endif %}" role="button" href="{% url 'asset-cabinet-update' object.id %}">
            <i class="fa fa-edit fa-fw"></i>编辑
        </a>
        <a title="删除" id="del_{{ object.id }}" class="btn btn-danger btn-xs {% if not perms.asset.delete_cabinetmodel %}disabled{% endif %}" role="button" href="{% url 'asset-cabinet-delete' object.id %}">
            <i class="fa fa-trash-o fa-fw"></i>删除
        </a>
    </td>
{% endblock %}

{% block extjs-dt-col %}
    { "orderable": false, "targets": [5, 6] },
{% endblock %}

templates/asset/cabinet_update_page.html
{% extends "base_form_page.html" %}

{% block title %}MtOps2 | 更新机柜信息{% endblock %}

{% block page-header %}更新机柜信息{% endblock %}

templates/asset/hardware_create_page.html
{% extends "base_form_page.html" %}

{% block title %} MtOps | 创建硬件信息 {% endblock %}

{% block page-header %}创建硬件信息{% endblock %}

templates/asset/hardware_list_page.html
{% extends "base_table_page.html" %}

{% block title %}MtOps2 | 硬件列表{% endblock %}

{% block page-header %}硬件列表{% endblock %}

{% block panel-heading %}
    <a href="{% url 'asset-hardware-create' %}" class="btn btn-success btn-sm {% if not perms.asset.add_hardwaremodel %}disabled{% endif %}" role="button">
        <i class="fa fa-plus-circle fa-fw"></i>创建硬件
    </a>
{% endblock %}

{% block thead-tr-th %}
    <th>ID</th>
    <th>型号</th>
    <th>cpu型号</th>
    <th>cpu个数</th>
    <th>内存／G</th>
    <th>磁盘类型</th>
    <th>磁盘个数</th>
    <th>存储容量／G</th>
    <th>网卡速率</th>
    <th>网卡个数</th>
    <th>远程管理支持</th>
    <th>双电支持</th>
    <th>添加时间</th>
    <th>操作</th>
{% endblock %}

{% block tbody-tr-td %}
    <td>{{ object.id }}</td>
    <td>{{ object.model }}</td>
    <td>{{ object.cpu }}</td>
    <td>{{ object.cpu_total }}</td>
    <td>{{ object.memory }}</td>
    <td>{{ object.disk_type }}</td>
    <td>{{ object.disk_total }}</td>
    <td>{{ object.storage }}</td>
    <td>{{ object.network_card_rate }}</td>
    <td>{{ object.network_card_total }}</td>
    <td>{{ object.get_drac_display }}</td>
    <td>{{ object.get_standby_power_display }}</td>
    <td>{{ object.put_date }}</td>
    <td>
        <a title="编辑" id="edit_{{ object.id }}" class="btn btn-success btn-xs {% if not perms.asset.change_hardwaremodel %}disabled{% endif %}" role="button" href="{% url 'asset-hardware-update' object.id %}">
            <i class="fa fa-edit fa-fw"></i>编辑
        </a>
        <a title="删除" id="del_{{ object.id }}" class="btn btn-danger btn-xs {% if not perms.asset.delete_hardwaremodel %}disabled{% endif %}" role="button" href="{% url 'asset-hardware-delete' object.id %}">
            <i class="fa fa-trash-o fa-fw"></i>删除
        </a>
    </td>
{% endblock %}

{% block extjs-dt-col %}
    { "orderable": false, "targets": [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]},
{% endblock %}

templates/asset/hardware_update_page.html
{% extends "base_form_page.html" %}

{% block title %}MtOps2 | 更新硬件信息{% endblock %}

{% block page-header %}更新硬件信息{% endblock %}

templates/asset/host_list_page.html
{% extends "base_table_page.html" %}

{% block title %}MtOps2 | 主机列表{% endblock %}

{% block page-header %}主机列表{% endblock %}

{% block panel-heading %}
    <a href="{% url 'asset-host-create' %}" class="btn btn-success btn-sm {% if not perms.asset.add_hostmodel %}disabled{% endif %}" role="button">
        <i class="fa fa-plus-circle fa-fw"></i>创建主机
    </a>
{% endblock %}

{% block thead-tr-th %}
    <th>主机 ID</th>
    <th>主机名</th>
    <th>所属机柜</th>
    <th>操作系统</th>
    <th>网卡1 IP</th>
    <th>网卡2 IP</th>
    <th>网卡3 IP</th>
    <th>网卡4 IP</th>
    <th>网卡1 mac</th>
    <th>网卡2 mac</th>
    <th>网卡3 mac</th>
    <th>网卡4 mac</th>
    <th>状态</th>
    <th>添加时间</th>
    <th>操作</th>
{% endblock %}

{% block tbody-tr-td %}
    <td>{{ object.id }}</td>
    <td><a href="{% url 'asset-host-detail' object.id %}">{{ object.host_name }}</td>
    <td>{{ object.cabinet }}</td>
    <td>{{ object.os }}</td>
    <td>{{ object.ip1 }}</td>
    <td>{{ object.ip2 }}</td>
    <td>{{ object.ip3 }}</td>
    <td>{{ object.ip4 }}</td>
    <td>{{ object.mac1 }}</td>
    <td>{{ object.mac2 }}</td>
    <td>{{ object.mac3 }}</td>
    <td>{{ object.mac4 }}</td>
    <td>{{ object.get_status_display }}</td>
    <td>{{ object.put_date }}</td>
    <td>
        <a title="编辑" id="edit_{{ object.id }}" class="btn btn-success btn-xs {% if not perms.asset.change_hostmodel %}disabled{% endif %}" role="button" href="{% url 'asset-host-update' object.id %}">
            <i class="fa fa-edit fa-fw"></i>编辑
        </a>
        <a title="删除" id="del_{{ object.id }}" class="btn btn-danger btn-xs {% if not perms.asset.delete_hostmodel %}disabled{% endif %}" role="button" href="{% url 'asset-host-delete' object.id %}">
            <i class="fa fa-trash-o fa-fw"></i>删除
        </a>
    </td>
{% endblock %}

{% block extjs-dt-col %}
    {"targets": [6, 7, 8, 10, 11, 12], "visible": false},
{% endblock %}

templates/asset/host_update_page.html
{% extends "base_form_page.html" %}

{% block title %}MtOps2 | 更新主机信息{% endblock %}

{% block page-header %}更新主机信息{% endblock %}

templates/asset/idc_create_page.html
{% extends "base_form_page.html" %}

{% block title %}MtOps2 | 创建机房{% endblock %}

{% block page-header %}创建机房{% endblock %}

templates/asset/idc_list_page.html
{% extends "base_table_page.html" %}

{% block title %}MtOps2 | 机房列表{% endblock %}

{% block page-header %}机房列表{% endblock %}

{% block panel-heading %}
    <a href="{% url 'asset-idc-create' %}" class="btn btn-success btn-sm {% if not perms.asset.add_idcmodel %}disabled{% endif %}" role="button">
        <i class="fa fa-plus-circle fa-fw"></i>创建机房
    </a>
{% endblock %}

{% block thead-tr-th %}
    <th>ID</th>
    <th>名称</th>
    <th>地址</th>
    <th>联系人</th>
    <th>电话</th>
    <th>链路类型</th>
    <th>带宽／Gbps</th>
    <th>机柜数量</th>
    <th>供电类型</th>
    <th>提交日期</th>
    <th>状态</th>
    <th>操作</th>
{% endblock %}

{% block tbody-tr-td %}
    <td>{{ object.id }}</td>
    <td>{{ object.name }}</td>
    <td>{{ object.address }}</td>
    <td>{{ object.contacts }}</td>
    <td>{{ object.phone }}</td>
    <td>{{ object.get_link_type_display }}</td>
    <td>{{ object.bandwidth }}</td>
    <td>{{ object.cabinet_total }}</td>
    <td>{{ object.get_power_type_display }}</td>
    <td>{{ object.put_date }}</td>
    <td>{{ object.get_idc_status_display }}</td>
    <td>
        <a title="编辑" id="edit_{{ object.id }}" class="btn btn-success btn-xs {% if not perms.asset.change_idcmodel %}disabled{% endif %}" role="button" href="{% url 'asset-idc-update' object.id %}">
            <i class="fa fa-edit fa-fw"></i>编辑
        </a>
        <a title="删除" id="del_{{ object.id }}" class="btn btn-danger btn-xs {% if not perms.asset.delete_idcmodel %}disabled{% endif %}" role="button" href="{% url 'asset-idc-delete' object.id %}">
            <i class="fa fa-trash-o fa-fw"></i>删除
        </a>
    </td>
{% endblock %}

{% block extjs-dt-col %}
    { "orderable": false, "targets": [2, 3, 5, 7, 8]},
{% endblock %}

templates/asset/idc_update_page.html
{% extends "base_form_page.html" %}

{% block title %}MtOps2 | 更新机房信息{% endblock %}

{% block page-header %}更新机房信息{% endblock %}

templates/asset/project_create_page.html
{% extends "base_form_page.html" %}

{% block title %} MtOps | 创建软件项目 {% endblock %}

{% block page-header %}创建软件项目{% endblock %}

templates/asset/project_list_page.html
{% extends "base_table_page.html" %}

{% block title %} MtOps2 | 软件资产项目列表 {% endblock %}

{% block page-header %}软件项目{% endblock %}

{% block panel-heading %}
    <a href="{% url 'asset-project-create' %}" class="btn btn-success btn-sm {% if not perms.asset.add_projectmodel %}disabled{% endif %}" role="button">
        <i class="fa fa-plus-circle fa-fw"></i>创建项目
    </a>
{% endblock %}

{% block thead-tr-th %}
    <th>项目ID</th>
    <th>项目名称</th>
    <th>项目别名</th>
    <th>创建时间</th>
    <th>项目备注</th>
    <th>操作</th>
{% endblock %}

{% block tbody-tr-td %}
    <td>{{ object.id}}</td>
    <td>{{ object.project_name}}</td>
    <td>{{ object.project_alias }}</td>
    <td>{{ object.put_date }}</td>
    <td>
        <a class='click_modal' href="{#{% url 'asset-project-detail' object.id %}#}" data-placement="bottom" title="项目描述">
            <i class="fa fa-eye fa-fw"></i>点击查看
        </a>
    </td>
    <td>
        <a title="编辑" id="edit_{{ object.id }}" class="btn btn-success btn-xs {% if not perms.asset.change_projectmodel %}disabled{% endif %}" role="button" href="{% url 'asset-project-update' object.id %}">
            <i class="fa fa-edit fa-fw"></i>编辑
        </a>
        <a title="删除" id="del_{{ object.id }}" class="btn btn-danger btn-xs {% if not perms.asset.delete_projectmodel %}disabled{% endif %}" role="button" href="{% url 'asset-project-delete' object.id %}">
            <i class="fa fa-trash-o fa-fw"></i>删除
        </a>
    </td>
{% endblock %}