MtOps2/urls.py
#-*- coding:utf8 -*-
"""MtOps2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from djauth_ext.forms import UserPwdUpdateForm


urlpatterns = [
    url( # grappelli URLS，在 url(r'^admin/', include(admin.site.urls)) 之前引用
        r'^grappelli/', include('grappelli.urls')
       ),
    url( # admin URL
        r'^admin/', include(admin.site.urls)
       ),
    url( # 包含 asset URL
        r'^asset/', include('asset.urls')
       ),
    url( # 包含 code_update URL
        r'^code-update/', include('code_update.urls')
       ),
    url(
        r'^dbop/', include('dbop.urls')
       ),
]

urlpatterns += [ # 使用 Django auth 提供的登录、注销视图
    url( # 平台登录
        r'^auth/user/login/$', auth_views.login, {'template_name': 'login_page.html'}, name='user-login'
       ),
    url( # 用户注销
        r'^auth/user/logout/$', auth_views.logout_then_login, name='user-logout'
       ),
    url( # 用户密码修改
        r'^auth/user/pwd-change/$', auth_views.password_change, {'template_name': 'djauth_ext/pwd_update_page.html', 'password_change_form': UserPwdUpdateForm,
        'post_change_redirect': auth_views.logout_then_login},
        name='djauth_ext-userpwd-change'
       ),
    url( # 包含 djauth_ext URL
        r'auth/', include('djauth_ext.urls')
       ),
]

code_update/urls.py
#-*- coding:utf8 -*-
from django.conf.urls import url

from views import (ProjectUpdateView, ProjectListView, TaskCreateView, TaskListView,
                   TaskUpdateView, TaskDeleteView, TaskRunLogView)


urlpatterns = [
    url( # 软件项目注册
        r'project/(?P<project_id>\d+)/update/$', ProjectUpdateView.as_view(),
        name='code-project-update',
       ),
    url( # 软件项目列表
        r'project/list/$', ProjectListView.as_view(),
        name='code-project-list',
       ),
    url( # 上线任务创建
        r'task/create/$', TaskCreateView.as_view(),
        name='code-task-create',
       ),
    url( # 上线任务更新
        r'task/(?P<task_id>\d+)/update/$', TaskUpdateView.as_view(),
        name='code-task-update',
       ),
    url( # 上线任务删除
        r'task/(?P<task_id>\d+)/delete/$', TaskDeleteView.as_view(),
        name='code-task-delete',
       ),
    url( # 查看后台任务执行输出
        r'task/(?P<task_id>\d+)/runlog/$', TaskRunLogView.as_view(),
        name='code-task-runlog',
       ),
    url( # 上线任务列表
        r'task/list/$', TaskListView.as_view(),
        name='code-task-list',
       ),
]

dbop/urls.py
# -*-coding:utf8 -*-
from django.conf.urls import url
from views import (CTTaskCreateView, CTTaskUpdateView, CTTaskDeleteView,
                   CTTaskListView, ct_sub_task_create, )#ajax_cors_agent)

urlpatterns = [
    url( # 普通建表任务创建
        r'ct-task/create/$', CTTaskCreateView.as_view(),
        name='dbop-ct_task-create',
       ),
    url( # 更新普通建表任务
        r'ct-task/(?P<ct_task_id>\d+)/update/$', CTTaskUpdateView.as_view(),
        name='dbop-ct_task-update',
       ),
    url(
        r'ct-task/(?P<ct_task_id>\d+)/add-sql/$', ct_sub_task_create,
        name="dbop-ct_task-addsql",
       ),
    url( # 删除任务
        r'ct-task/(?P<ct_task_id>\d+)/delete/$', CTTaskDeleteView.as_view(),
        name='dbop-ct_task-delete',
       ),
    url( # 普通建表任务列表
        r'ct-task/list/$', CTTaskListView.as_view(),
        name='dbop-ct_task-list',
       ),
#    url(
#        r'cttask/(?P<ctmaintask_id>\d+)/detail/', 
#       ),
#    url( # ajax 代理视图
#        r'cttask/sql-textarex/ajaxpost-dbapi-check/$', ajax_cors_agent,
#        name='dbop-ajaxcors-agent',
#       ),
]

code_update/models.py
# -*- coding:utf8 -*-
from django.db import models

from django.db.models import Q

from django.contrib.auth.models import User

from asset.models import ProjectModel

from django.dispatch import receiver

from django.db.models.signals import post_save

from guardian.shortcuts import get_objects_for_user


class ProjectProxyModel(ProjectModel):
    """
    asset 应用 Project 模型代理
    """
    class Meta:
        proxy = True
        permissions = (
            ("view_projectproxymodel", "Can see available project"),
        )
        verbose_name = u'软件项目代理模型'
        verbose_name_plural = u'软件项目代理模型'


class ProjectExtModel(models.Model):
    """
    为 asset 资产应用 ProjectModel 扩展
    以下字段
    """
    project = models.OneToOneField(ProjectModel, verbose_name=u'绑定项目', db_column='project')
    run_script = models.CharField(verbose_name=u'上线脚本', db_column='run_script', max_length=30, default=u'未绑定')

    def __unicode__(self):
        return self.run_script

    class Meta:
        db_table = 'code_projectext'
        verbose_name = u'软件项目扩展属性'
        verbose_name_plural = u'软件项目扩展属性'


class TaskModel(models.Model):
    """
    上线任务模型
    """
    _SCHEDULE = (
                 ('0', u'待上线'),
#                 ('1', u'审核通过'),
#                 ('2', u'审核未通过'),
                 ('3', u'版本更新'),
                 ('4', u'版本回滚'),
                 ('5', u'查看上线变动'),
                )
    _STATUS = (
               ('0', u'任务进行中...'),
               ('1', u'任务 DONE'),
              )

    user = models.ForeignKey(User, verbose_name=u"代码上线责任人", db_column='user')
    project = models.ForeignKey(ProjectProxyModel, verbose_name=u"上线项目", db_column='project')
    code_version = models.CharField(verbose_name=u"项目版本号", db_column='code_version', max_length=100, default='master')
    put_date = models.DateTimeField(verbose_name=u"任务提交时间", db_column='put_date', auto_now_add=True)
    yw_user = models.CharField(verbose_name=u"运维责任人", db_column='yw_user', max_length=100, default='-')
    schedule = models.CharField(verbose_name=u"上线进度", db_column='schedule', choices= _SCHEDULE, max_length=1, default='0')
    status = models.CharField(verbose_name=u"任务状态", db_column='status', choices=_STATUS, max_length=1, default='0')
    script_output_log = models.TextField(verbose_name=u"上线脚本执行输出", db_column='script_output_log',
                                         default='==================== *下屏显示后台脚本执行输出* ====================\n',
                                        )
    update_count = models.IntegerField(verbose_name=u"更新操作次数", db_column='update_count', default='0')
    rollback_count = models.IntegerField(verbose_name=u"回滚操作次数", db_column='rollback_count', default='0')
    remark = models.CharField(verbose_name=u"备注信息", db_column='remark', max_length=50, help_text=u"如果需要可提交 50 字符长度的备注信息",
                              default='-'
                             )

    def __unicode__(self):
        return self.project.project_name

    def save(self, *args, **kwargs):
        """
        重写 save 方法，添加操作计数
        """
        if self.schedule == '3':
            self.update_count += 1
        elif self.schedule == '4':
            self.rollback_count += 1
        super(TaskModel, self).save(*args, **kwargs)

    class Meta:
        db_table = 'code_task'
        verbose_name = u'代码上线任务'
        verbose_name_plural = u'代码上线任务'


@receiver(post_save, sender=ProjectModel) # 绑定 Django 内建 post_save 信号
def project_ext_create(sender, instance, created, **kwargs):
    if created: # 判断信号事件是否为创建新纪录
        regproject = ProjectExtModel(project=instance)
        regproject.save()

code_update/forms.py
# -*- coding:utf8 -*-
from django import forms

from models import ProjectExtModel, TaskModel


class ProjectUpdateForm(forms.ModelForm):
    """
    项目注册表单
    """
    class Meta:
        model = ProjectExtModel
        fields = ['run_script']
        widgets = {
                   'run_script': forms.TextInput(attrs={'class': 'form-control',}),
                  }

class TaskCreateForm(forms.ModelForm):
    """
    上线任务创建表单
    """
    class Meta:
        model = TaskModel
        fields = ['project', 'code_version', 'remark']
        widgets = {
                   'project': forms.Select(attrs={'class': 'form-control',},),
                   'code_version': forms.TextInput(attrs={'class': 'form-control',}),
                   'remark': forms.TextInput(attrs={'class': 'form-control',}),
                  }


class TaskUpdateForm(forms.ModelForm):
    """
    上线任务更新表单
    """
    _SCHEDULE = (
        ('3', u'版本更新'),
        ('4', u'版本回滚'),
        ('5', u'查看上线变动'),
    )
    schedule = forms.CharField(label=u'上线进度', widget=forms.Select(choices=_SCHEDULE, attrs={'class': 'form-control',}))
    class Meta:
        model = TaskModel
        fields = ['schedule', 'status']
        widgets = {
                   'status': forms.Select(attrs={'class': 'form-control',},),
                  }

code_update/views.py
# -*- coding:utf8 -*-
from django.core.urlresolvers import reverse_lazy

from django.contrib.auth.decorators import login_required, permission_required

from django.utils.decorators import method_decorator

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from models import ProjectProxyModel, ProjectExtModel, TaskModel

from forms import ProjectUpdateForm, TaskCreateForm, TaskUpdateForm

from guardian.shortcuts import get_objects_for_user # 第三方库，object 级别权限控制相关

from tasks import code_task


class ProjectUpdateView(UpdateView):
    """
    项目绑定上线脚本
    """
    model = ProjectExtModel
    pk_url_kwarg = 'project_id'
    form_class = ProjectUpdateForm
    template_name = 'code_update/project_update_page.html'
    success_url = reverse_lazy('code-project-list')

    @method_decorator(login_required)
    @method_decorator(permission_required('code_update.change_projectextmodel', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(ProjectUpdateView, self).dispatch(*args, **kwargs)


class ProjectListView(ListView):
    """
    项目列表
    """
    model = ProjectExtModel
    template_name = 'code_update/project_list_page.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectListView, self).dispatch(*args, **kwargs)


class TaskCreateView(CreateView):
    """
    创建上线任务
    """
    model = TaskModel
    form_class = TaskCreateForm
    template_name = 'code_update/task_create_page.html'
    success_url = reverse_lazy('code-task-list')

    def get_context_data(self, **kwargs):
        """
        增加额外的渲染对象
        """
        projects = get_objects_for_user(self.request.user, 'asset.view_projectproxymodel') # 获取当前登录用户所拥有可视权限的项目，用于前端 <select> 选项的渲染
        if 'projects' not in kwargs:
            kwargs['projects'] = projects
        return super(TaskCreateView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        """
        为非用户提交字段在后台自动创建相应的初始值
        """
        form.instance.user = self.request.user
        return super(TaskCreateView, self).form_valid(form)

    @method_decorator(login_required)
    @method_decorator(permission_required('code_update.add_taskmodel', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(TaskCreateView, self).dispatch(*args, **kwargs)


class TaskUpdateView(UpdateView):
    """
    更新上线任务
    """
    model = TaskModel
    pk_url_kwarg = 'task_id'
    form_class = TaskUpdateForm
    template_name = 'code_update/task_update_page.html'
    success_url = reverse_lazy('code-task-list')

    def form_valid(self, form):
        """
        在响应 HTTP 请求之前，将后台任务与相关参数做入队操作
        """
        form.instance.yw_user = self.request.user.last_name + self.request.user.first_name # 将登录用户作为操作责任人存至相应字段

        if form.instance.schedule == '3':
            action = 'update'
        elif form.instance.schedule == '4':
            action = 'rollback'
        elif form.instance.schedule == '5':
            action = 'checkdiff'

        task_id = form.instance.id
        code_version = form.instance.code_version
        run_script = form.instance.project.projectextmodel.run_script
        mod_name = form.instance.project.project_alias

        code_task.delay(run_script, mod_name, action, code_version, task_id)

        return super(TaskUpdateView, self).form_valid(form)

    @method_decorator(login_required)
    @method_decorator(permission_required('code_update.change_taskmodel', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(TaskUpdateView, self).dispatch(*args, **kwargs)
    

class GetDeleteMixin(object):
    """
    Django 提供的 DeleteView 通用试图默认 get() 方法用做渲染删除成功页面，
    由于项目使用 GET 方式删除，所以这里重写 get() 方法调用 delete()。
    """
    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class TaskDeleteView(GetDeleteMixin, DeleteView):
    """
    删除上线任务
    """
    model = TaskModel
    pk_url_kwarg = 'task_id'
    success_url = reverse_lazy('code-task-list')

    @method_decorator(login_required)
    @method_decorator(permission_required('code_update.delete_taskmodel', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(TaskDeleteView, self).dispatch(*args, **kwargs)


class TaskRunLogView(DetailView):
    """
    显示后台任务输出
    """
    model = TaskModel
    pk_url_kwarg = 'task_id'
    template_name = 'code_update/task_runlog_page.html'

    @method_decorator(login_required)
    @method_decorator(permission_required('code_update.add_taskmodel', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(TaskRunLogView, self).dispatch(*args, **kwargs)


class TaskListView(ListView):
    """
    任务列表
    """
    model = TaskModel
    ordering = '-put_date'
    template_name = 'code_update/task_list_page.html'

    def get_queryset(self):
        """
        过滤出当前登录用户拥有权限的纪录
        """
        queryset = super(TaskListView, self).get_queryset()
        projects = get_objects_for_user(self.request.user, 'asset.view_projectproxymodel')

        if projects:
            new_queryset = queryset.filter(project__in=projects)
        else:
            new_queryset = []

        return new_queryset

    @method_decorator(login_required)
    @method_decorator(permission_required('code_update.add_taskmodel', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(TaskListView, self).dispatch(*args, **kwargs)

templates/code_update/project_list_page.html
{% extends "base_table_page.html" %}

{% block title %} MtOps2 | 上线项目列表 {% endblock %}

{% block page-header %}上线项目{% endblock %}

{% block thead-tr-th %}
    <th>项目ID</th>
    <th>项目名称</th>
    <th>项目别名</th>
    <th>绑定脚本</th>
    <th>操作</th>
{% endblock %}

{% block tbody-tr-td %}
    <td>{{ object.project.id }}</td>
    <td>{{ object.project.project_name }}</td>
    <td>{{ object.project.project_alias }}</td>
    <td>{{ object.run_script }}</td>
    <td>
        <a title="绑定脚本" id="edit_{{ object.id }}" class="btn btn-success btn-xs {% if not perms.code_update.change_projectextmodel %}disabled{% endif %}" role="button" href="{% url 'code-project-update' object.id %}">
            <i class="fa fa-edit fa-fw"></i>绑定脚本
        </a>
    </td>
{% endblock %}

{% block extend-js %}
    {{ block.super }}
    <script>
        $(function () { // 激活表格排序插件
            $('#myTable').DataTable({
                "pageLength": 50,
                "order": [[ 0, "desc" ]],
                "columnDefs": [
                    { "orderable": false, "targets": 4 },
                ],
            });
        });
    </script>
{% endblock %}

templates/code_update/project_update_page.html
{% extends "base_form_page.html" %}

{% block title %}MtOps2 | 指定上线脚本{% endblock %}

{% block page-header %} 指定上线脚本{% endblock %}

templates/code_update/task_create_page.html
{% extends "base_form_page.html" %}

{% block title %}MtOps2 | 创建代码上线任务{% endblock %}

{% block page-header %} 创建代码上线任务{% endblock %}

{% block custom_input %}
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.project.id_for_label }}" class="col-lg-2 control-label">{{ form.project.label }}</label>
        <div class="col-lg-8">
            {% if form.project.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.project.errors }}
                </div>
            {% endif %}
            <select class="form-control" name="project">
                {% for project in projects %}
                    <option value="{{ project.id }}">{{ project.project_name }}</option>
                {% endfor %}
            </select>
            {% if form.project.help_text %}
                <p class="help-block">{{ form.project.help_text }}</p>
            {% endif %}
        </div>
    </div>
    <hr />
    <div class="form-group">
        <label for="{{ form.code_version.id_for_label }}" class="col-lg-2 control-label">{{ form.code_version.label }}</label>
        <div class="col-lg-8">
            {% if form.code_version.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.code_version.errors }}
                </div>
            {% endif %}
            {{ form.code_version }}
            {% if form.code_version.help_text %}
                <p class="help-block">{{ form.code_version.help_text }}</p>
            {% endif %}
        </div>
    </div>
    <hr />
    <div class="form-group">
        <label for="{{ form.remark.id_for_label }}" class="col-lg-2 control-label">{{ form.code_version.label }}</label>
        <div class="col-lg-8">
            {% if form.remark.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ form.remark.errors }}
                </div>
            {% endif %}
            {{ form.remark }}
            {% if form.remark.help_text %}
                <p class="help-block">{{ form.remark.help_text }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/code_update/task_list_page.html
{% extends "base_table_page.html" %}

{% block title %} MtOps2 | 项目上线任务 {% endblock %}

{% block page-header %}项目上线任务{% endblock %}

{% block panel-heading %}
    <a href="{% url 'code-task-create' %}" class="btn btn-success btn-sm {% if not perms.code_update.add_taskmodel %}disabled{% endif %}" role="button">
        <i class="fa fa-plus-circle fa-fw"></i>创建任务
    </a>
{% endblock %}

{% block thead-tr-th %}
    <th>任务ID</th>
    <th>项目</th>
    <th>版本</th>
    <th>责任人</th>
    <th>操作人</th>
    <th>创建时间</th>
    <th>更新次数</th>
    <th>回滚次数</th>
    <th>进度</th>
    <th>任务状态</th>
    <th>操作</th>
{% endblock %}

{% block tbody-tr-td %}
    <td>{{ object.id}}</td>
    <td>{{ object.project.project_name}}</td>
    <td>{{ object.code_version }}</td>
    <td>{{ object.user }}</td>
    <td>{{ object.yw_user }}</td>
    <td>{{ object.put_date }}</td>
    <td>{{ object.update_count }}</td>
    <td>{{ object.rollback_count }}</td>
    <td>{{ object.get_schedule_display }}</td>
    <td>{{ object.get_status_display }}</td>
    <td>
        <a title="编辑" class="btn btn-success btn-xs {% if not perms.code_update.change_taskmodel %}disabled{% endif %}" role="button" href="#">
            <i class="fa fa-edit fa-fw"></i>编辑
        </a>
        <a title="删除" class="btn btn-danger btn-xs {% if not perms.code_update.delete_taskmodel %}disabled{% endif %}" role="button" href="#">
            <i class="fa fa-trash-o fa-fw"></i>删除
        </a>
        <a title="操作LOG" id="detail_{{ object.id }}" class="btn btn-info btn-xs" role="button" href="{% url 'code-task-runlog' object.id %}">
            <i class="fa fa-print fw"></i>打印LOG
        </a>
    </td>
{% endblock %}

{% block extend-js %}
    {{ block.super }}
    <script>
        $(function () { // 激活表格排序插件
            $('#myTable').DataTable({
                //responsive: true,
                "pageLength": 50,
                "order": [[ 0, "desc" ]],
                "columnDefs": [
                    { "orderable": false, "targets": 10 },
                ],
            });
        });
    </script>
{% endblock %}

templates/code_update/task_runlog_page.html
{% extends "base_page.html" %}

{% block title %}MtOps2 | 上线任务执行日志{% endblock %}

{% block extend-css %}
    <style type="text/css">
        .terminal {
            background-color:#222;
            color:#00FF00;
        }
    </style>
{% endblock %}

{% block page-header %}上线任务执行日志{% endblock %}

{% block page-content %}
    <div class="terminal">
        <p>{{ object.script_output_log|linebreaks }}</p>
    </div>
{% endblock %}

templates/code_update/task_update_page.html
{% extends "base_form_page.html" %}

{% block title %} MtOps | 更新上线任务 {% endblock %}

{% block page-header %}更新上线任务{% endblock %}